name: nowje-unit-test-exchange-maven-plugin-pull-request

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build
      run: mvn clean install
    - name: Coverage with Coveralls
      run: mvn jacoco:prepare-agent package jacoco:report
